# Profile
# Server config
server:
  port: 8081
  contextPath: /snow
  compression:
      enabled: true
      mime-types: application/json,application/xml,text/html,text/xml,text/plain
spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/newdb
      username: root
      password: qtrh2130
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

logging:
  level:
    com.ibatis:ERROR