# Server config
server:
  port: 8080
  contextPath: /snow
  compression:
      enabled: true
      mime-types: application/json,application/xml,text/html,text/xml,text/plain
# Profile
# 默认的profile为dev，其他环境通过指定启动参数使用不同的profile，比如：
# 测试环境：java -jar snow.jar --spring.profiles.active=dev
# 生产环境：java -jar snow.jar --spring.profiles.active=prod
spring:
  profiles:
    active: dev